redis:
  message:
    addr: "127.0.0.1:6379"
    db: 0
  common:
    addr: "127.0.0.1:6379"
    db: 0
  session:
    addr: "127.0.0.1:6379"
    db: 0
mongodb:
  host: "localhost:27017"
  auth: "admin"
  user: "admin"
  pass: ""
  poollimit: 100
